#################################################################
### Changes require restarting the application to take effect ###
#################################################################

### if set to true will open the detail view of the vocab card
auto_open = true

##################################################################
### The following config options will need you to be logged in ###
##################################################################

### get the sid cookie from your browser and paste it here, then uncomment the option
### WARNING:
### Anyone who knows the value below can log into jpdb as you and use your account,
### which may let them find out your email address, delete your decks, and so on.
### Please hide it or remove it when sharing your configuration file with someone else.
# session_id = "paste your sid value here"

### set this option to the id of the deck where you want vocab cards added automatically
### you can get the id by clicking on the detail view of a deck and looking at your browser url bar
### if this option is not set, it will not add cards automatically
# auto_add = 0

### uncomment this option to automatically add cards added via jpdb-connect to
### the front of your review queue (FORQ)
### it will work even if the card is locked
### it won't work if the card is suspendend or not in any deck (but auto_add helps here)
# auto_forq = true

### works like auto_forq except that it unlocks the card
# auto_unlock = true


### automatically marks card as forgotten
### this inserts a failed review for the card
### and removes it from all decks which are marked as known
# auto_forget = true

### automatically add the sentence sent via yomichan to the jpdb card
### Be aware that you can only have one custom example sentence per card.
### If there already is one, it will be overwritten.
### At the moment this option will only work if the card and the mined
### sentence share the same exact spelling for the added word.
### For example if you add 此れ while the sentence uses これ it will not work.
### If no sentence is provided, updating will be skipped.
# add_mined_sentences = true

### automatically add the definition sent via yomichan as a custom definition
### If the definition provided is empty, nothing will happen and the
### default definitions will be left in place. Otherwise, this setting will
### disable all default definitions leaving only the custom definition shown.
### This will overwrite any custom definition that may have been previously added to the card.
# add_custom_definition = true

#################################################################
### the following options are for power users and developers ####
#################################################################

### change the ip jpdb-connect binds to
### default is 127.0.0.1
# ip = "127.0.0.1"

### change the port jpdb-connect uses
### default is 3030
# port = 3030

### for debugging and development purposes
# loglevels are: Trace, Debug, Info, Warn, Error
# default level is Info
# log_level = "Trace"
